server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///sell?useSSL=false&amp&serverTimezone=UTC&characterEncoding=utf-8
  jpa:
    show-sql: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 192.168.1.15
